import { Theme } from './types'

export const defaultTheme: Theme = {
  colors: {
    primary: '#1890ff',
    success: '#52c41a',
    warning: '#faad14',
    error: '#ff4d4f',
    info: '#1890ff',

    text: 'rgba(0, 0, 0, 0.88)',
    textSecondary: 'rgba(0, 0, 0, 0.65)',
    textTertiary: 'rgba(0, 0, 0, 0.45)',
    textDisabled: 'rgba(0, 0, 0, 0.25)',

    background: '#ffffff',
    backgroundSecondary: '#fafafa',
    backgroundTertiary: '#f5f5f5',
    backgroundHover: '#fafafa',

    border: '#d9d9d9',
    borderSecondary: '#f0f0f0',
    borderHover: '#4096ff',
    white: '#ffffff',
  },

  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 48,
  },

  borderRadius: {
    xs: 2,
    sm: 4,
    md: 6,
    lg: 8,
    xl: 12,
  },

  fontSize: {
    xs: 12,
    sm: 14,
    md: 16,
    lg: 18,
    xl: 20,
    xxl: 24,
  },

  fontWeight: {
    light: 300,
    normal: 400,
    medium: 500,
    semibold: 600,
    bold: 700,
  },

  lineHeight: {
    tight: 1.25,
    normal: 1.5,
    relaxed: 1.75,
  },

  shadows: {
    sm: '0 1px 2px rgba(0, 0, 0, 0.03)',
    md: '0 1px 6px rgba(0, 0, 0, 0.03)',
    lg: '0 4px 12px rgba(0, 0, 0, 0.15)',
    xl: '0 8px 24px rgba(0, 0, 0, 0.15)',
  },

  transitions: {
    fast: 'all 0.1s ease-in-out',
    normal: 'all 0.2s cubic-bezier(0.645, 0.045, 0.355, 1)',
    slow: 'all 0.3s ease-in-out',
  },

  breakpoints: {
    xs: '480px',
    sm: '576px',
    md: '768px',
    lg: '992px',
    xl: '1200px',
  },

  components: {
    pagination: {
      itemSize: '32px',
      itemBg: '#ffffff',
      itemActiveBg: '#ffffff',
      itemBorderRadius: '4px',
      itemColor: 'rgba(0, 0, 0, 0.88)',
      itemActiveColor: '#1890ff',
      itemHoverBg: '#ffffff',
      itemHoverColor: '#1890ff',
      fontSize: '14px',
    },
    button: {
      padding: {
        sm: '0 8px',
        md: '0 16px',
      },
      fontSize: {
        sm: '12px',
        md: '14px',
        lg: '16px',
      },
      borderRadius: {
        sm: '4px',
        md: '6px',
        lg: '8px',
      },
      rippleOpacity: 0.3,
    },
    checkbox: {
      size: {
        sm: '14px',
        md: '16px',
        lg: '20px',
      },
      borderRadius: '4px',
      borderColor: '#d9d9d9',
      checkedBorderColor: '#1890ff',
      checkedBg: '#1890ff',
      disabledBg: '#fafafa',
      labelColor: 'rgba(0, 0, 0, 0.88)',
      iconColor: '#ffffff',
      focusRingColor: '#1890ff',
    },
    radio: {
      size: {
        sm: '14px',
        md: '16px',
        lg: '20px',
      },
      dotSize: {
        sm: '6px',
        md: '8px',
        lg: '10px',
      },
      borderColor: '#d9d9d9',
      checkedBorderColor: '#1890ff',
      dotColor: '#1890ff',
      labelColor: 'rgba(0, 0, 0, 0.88)',
      focusRingColor: '#1890ff',
    },
    switch: {
      trackWidth: {
        sm: '28px',
        md: '36px',
        lg: '44px',
      },
      trackHeight: {
        sm: '16px',
        md: '20px',
        lg: '24px',
      },
      thumbSize: {
        sm: '12px',
        md: '16px',
        lg: '20px',
      },
      thumbOffset: {
        sm: '12px',
        md: '16px',
        lg: '20px',
      },
      checkedBg: '#1890ff',
      uncheckedBg: 'rgba(0, 0, 0, 0.25)',
      disabledBg: 'rgba(0, 0, 0, 0.25)',
      thumbBg: '#ffffff',
      labelColor: 'rgba(0, 0, 0, 0.88)',
      focusRingColor: '#1890ff',
    },
    message: {
      contentPadding: '8px 16px',
      contentBg: '#ffffff',
      contentColor: 'rgba(0, 0, 0, 0.88)',
      borderRadius: '8px',
      boxShadow:
        '0 3px 6px -4px rgba(0, 0, 0, 0.12), 0 6px 16px 0 rgba(0, 0, 0, 0.08), 0 9px 28px 8px rgba(0, 0, 0, 0.05)',
      zIndex: 1010,
    },
    modal: {
      maskColor: 'rgba(0, 0, 0, 0.45)',
      contentBg: '#ffffff',
      borderRadius: '8px',
      boxShadow:
        '0 3px 6px -4px rgba(0, 0, 0, 0.12), 0 6px 16px 0 rgba(0, 0, 0, 0.08), 0 9px 28px 8px rgba(0, 0, 0, 0.05)',
      headerPadding: '16px 24px',
      bodyPadding: '24px',
      footerPadding: '10px 16px',
      zIndex: 1000,
      padding: '24px',
    },
    progress: {
      trackColor: '#f5f5f5',
      successColor: '#52c41a',
      errorColor: '#ff4d4f',
      warningColor: '#faad14',
      infoColor: '#1890ff',
      fontSize: '14px',
    },
    steps: {
      descriptionColor: 'rgba(0, 0, 0, 0.45)',
      titleColor: 'rgba(0, 0, 0, 0.65)',
      subTitleColor: 'rgba(0, 0, 0, 0.45)',
      waitIconColor: 'rgba(0, 0, 0, 0.25)',
      processIconColor: '#1890ff',
      finishIconColor: '#1890ff',
      errorIconColor: '#ff4d4f',
      waitTitleColor: 'rgba(0, 0, 0, 0.45)',
      processTitleColor: 'rgba(0, 0, 0, 0.85)',
      finishTitleColor: 'rgba(0, 0, 0, 0.65)',
      errorTitleColor: '#ff4d4f',
      waitDescriptionColor: 'rgba(0, 0, 0, 0.45)',
      processDescriptionColor: 'rgba(0, 0, 0, 0.65)',
      finishDescriptionColor: 'rgba(0, 0, 0, 0.45)',
      errorDescriptionColor: '#ff4d4f',
      iconSize: '32px',
      dotSize: '8px',
      titleFontSize: '16px',
      descriptionFontSize: '14px',
    },
    input: {
      padding: {
        sm: '4px 8px',
        md: '6px 12px',
        lg: '8px 16px',
      },
      fontSize: {
        sm: '12px',
        md: '14px',
        lg: '16px',
      },
      borderRadius: '4px',
      activeBorderColor: '#40a9ff',
      hoverBorderColor: '#4096ff',
    },
    alert: {
      padding: '12px 16px',
      borderRadius: '8px',
      titleColor: 'rgba(0, 0, 0, 0.88)',
      descriptionColor: '#595959',
      iconSize: '18px',
      closeColor: '#8c8c8c',
      closeHoverColor: '#1f1f1f',
      focusRingColor: '#1677ff',
      info: {
        backgroundColor: '#e6f4ff',
        borderColor: '#91caff',
        accentColor: '#1677ff',
      },
      success: {
        backgroundColor: '#f6ffed',
        borderColor: '#b7eb8f',
        accentColor: '#52c41a',
      },
      warning: {
        backgroundColor: '#fffbe6',
        borderColor: '#ffe58f',
        accentColor: '#faad14',
      },
      error: {
        backgroundColor: '#fff2f0',
        borderColor: '#ffccc7',
        accentColor: '#ff4d4f',
      },
    },
    empty: {
      gap: {
        sm: '8px',
        md: '12px',
        lg: '16px',
      },
      padding: {
        sm: '20px 16px',
        md: '32px 20px',
        lg: '40px 24px',
      },
      imageWidth: {
        sm: '64px',
        md: '88px',
        lg: '112px',
      },
      imageHeight: {
        sm: '48px',
        md: '60px',
        lg: '72px',
      },
      imageRadius: '16px',
      imageBackground:
        'linear-gradient(135deg, rgba(22, 119, 255, 0.12), rgba(82, 196, 26, 0.08)), #fafafa',
      imageBorderColor: '#d9d9d9',
      imagePlaceholderColor: '#d9d9d9',
      titleColor: '#1f1f1f',
      descriptionColor: '#8c8c8c',
      actionGap: '8px',
    },
    skeleton: {
      gap: '12px',
      rowGap: '8px',
      avatarSize: '40px',
      blockHeight: '14px',
      borderRadius: '4px',
      shimmerBaseColor: 'rgba(0, 0, 0, 0.08)',
      shimmerHighlightColor: 'rgba(255, 255, 255, 0.55)',
    },
    spinLoading: {
      indicatorColor: '#1677ff',
      tipColor: '#8c8c8c',
      overlayBackground: 'rgba(255, 255, 255, 0.72)',
      overlayBackdropBlur: 'blur(0.5px)',
      size: {
        sm: '16px',
        md: '24px',
        lg: '36px',
      },
    },
    popover: {
      zIndex: 1060,
      minWidth: '220px',
      maxWidth: '320px',
      borderRadius: '8px',
      backgroundColor: '#ffffff',
      boxShadow: '0 8px 24px rgba(0, 0, 0, 0.14), 0 4px 10px rgba(0, 0, 0, 0.08)',
      borderColor: 'rgba(5, 5, 5, 0.08)',
      headerPadding: '12px 14px 0',
      bodyPadding: '12px 14px 14px',
      titleColor: 'rgba(0, 0, 0, 0.88)',
      titleFontSize: '14px',
      bodyColor: 'rgba(0, 0, 0, 0.65)',
      bodyFontSize: '13px',
    },
    popconfirm: {
      minWidth: '240px',
      titleColor: 'rgba(0, 0, 0, 0.88)',
      titleFontSize: '14px',
      descriptionColor: 'rgba(0, 0, 0, 0.65)',
      descriptionFontSize: '13px',
      descriptionMarginTop: '8px',
      actionsGap: '8px',
      actionsMarginTop: '14px',
    },
    drawer: {
      zIndex: 1000,
      maskColor: 'rgba(0, 0, 0, 0.45)',
      backdropBlur: 'blur(1px)',
      contentBg: '#ffffff',
      boxShadow:
        '0 6px 16px 0 rgba(0, 0, 0, 0.08), 0 3px 6px -4px rgba(0, 0, 0, 0.12), 0 9px 28px 8px rgba(0, 0, 0, 0.05)',
      headerPadding: '24px',
      bodyPadding: '24px',
      footerPadding: '24px',
      borderColor: '#f0f0f0',
      titleColor: 'rgba(0, 0, 0, 0.88)',
      titleFontSize: '18px',
    },
    tooltip: {
      zIndex: 1070,
      backgroundColor: 'rgba(0, 0, 0, 0.85)',
      contentColor: '#ffffff',
      boxShadow: '0 4px 12px rgba(0, 0, 0, 0.15)',
      borderRadius: '8px',
      padding: '6px 10px',
      maxWidth: '240px',
      fontSize: '12px',
    },
    dropdown: {
      zIndex: 1050,
      backgroundColor: '#ffffff',
      boxShadow:
        '0 3px 6px -4px rgba(0, 0, 0, 0.12), 0 6px 16px 0 rgba(0, 0, 0, 0.08), 0 9px 28px 8px rgba(0, 0, 0, 0.05)',
      borderRadius: '4px',
      padding: '4px 0',
    },
    menu: {
      itemHoverBg: '#f5f5f5',
      itemSelectedBg: '#e6f7ff',
      itemColor: 'rgba(0, 0, 0, 0.88)',
      itemHeight: '32px',
      itemPadding: '0 12px',
      fontSize: '14px',
      borderRadius: '4px',
    },
    datePicker: {
      cellWidth: '32px',
      cellHeight: '32px',
      cellPadding: '0',
      cellMargin: '2px',
      cellFontSize: '14px',
      cellBorderRadius: '4px',

      headerPadding: '12px 16px',
      headerHeight: '40px',
      headerFontSize: '14px',

      weekDayFontSize: '12px',

      cellActiveBg: '#1890ff',
      cellHoverBg: '#40a9ff',
      cellColor: 'rgba(0, 0, 0, 0.88)',
      cellActiveColor: '#ffffff',
      cellDisabledColor: 'rgba(0, 0, 0, 0.25)',

      borderColor: 'rgba(0, 0, 0, 0.06)',
      boxShadow:
        '0 6px 16px 0 rgba(0, 0, 0, 0.08), 0 3px 6px -4px rgba(0, 0, 0, 0.12), 0 9px 28px 8px rgba(0, 0, 0, 0.05)',
      zIndex: 1000,
    },
    tree: {
      nodeSelectedBg: '#e6f7ff',
      nodeHoverBg: '#f5f5f5',
      nodeColor: 'rgba(0, 0, 0, 0.88)',
      nodeSelectedColor: 'rgba(0, 0, 0, 0.88)',
      switcherColor: 'rgba(0, 0, 0, 0.45)',
      switcherHoverColor: '#1890ff',
      fontSize: '14px',
      borderRadius: '4px',
      indentSize: '24px',
    },
    select: {
      borderRadius: '4px',
      backgroundColor: '#ffffff',
      borderColor: '#d9d9d9',
      hoverBorderColor: '#4096ff',
      activeBorderColor: '#1890ff',
      placeholderColor: 'rgba(0, 0, 0, 0.25)',

      // Dropdown
      dropdownBg: '#ffffff',
      dropdownBoxShadow:
        '0 3px 6px -4px rgba(0, 0, 0, 0.12), 0 6px 16px 0 rgba(0, 0, 0, 0.08), 0 9px 28px 8px rgba(0, 0, 0, 0.05)',
      dropdownPadding: '4px 0',
      dropdownZIndex: 1050,
      dropdownMaxHeight: '256px',

      // Options
      optionSelectedBg: '#e6f7ff',
      optionHoverBg: '#f5f5f5',
      optionColor: 'rgba(0, 0, 0, 0.88)',
      optionSelectedColor: 'rgba(0, 0, 0, 0.88)',
      optionPadding: '0 12px',
      optionMinHeight: '32px',
      optionFontSize: '14px',

      // Tags
      tagBg: '#f5f5f5',
      tagColor: 'rgba(0, 0, 0, 0.88)',
      tagBorderColor: '#f0f0f0',
      tagHeight: '24px',
      tagPadding: '0 8px',
      tagFontSize: '12px',
      tagBorderRadius: '4px',

      // Sizes
      padding: {
        sm: '1px 8px',
        md: '3px 12px',
        lg: '6px 16px',
      },
      fontSize: {
        sm: '12px',
        md: '14px',
        lg: '16px',
      },
      minHeight: {
        sm: '20px',
        md: '24px',
        lg: '26px',
      },
    },

    form: {
      itemMarginBottom: '16px',
      labelColor: 'rgba(0, 0, 0, 0.88)',
      labelFontSize: '14px',
      labelMarginBottom: '8px',
      errorColor: '#ff4d4f',
      errorFontSize: '12px',
      errorMarginTop: '2px',
      errorMarginBottom: '2px',
    },
    tabs: {
      tabBarBorderColor: '#f0f0f0',
      tabBarBorderWidth: '1px',
      tabBarBackgroundColor: '#ffffff',
      tabItemColor: 'rgba(0, 0, 0, 0.88)',
      tabItemActiveColor: '#1890ff',
      tabItemHoverColor: '#40a9ff',
      tabItemDisabledColor: 'rgba(0, 0, 0, 0.25)',
      tabItemFontSize: '14px',
      tabItemPadding: '12px 16px',
      tabItemHorizontalGutter: '32px',
      tabItemVerticalGutter: '16px',
      inkBarColor: '#1890ff',
      inkBarHeight: '2px',
    },
    table: {
      headerBg: '#fafafa',
      headerColor: 'rgba(0, 0, 0, 0.85)',
      rowHoverBg: '#fafafa',
      borderColor: '#f0f0f0',
      bodyBg: '#ffffff',
      color: 'rgba(0, 0, 0, 0.88)',
      cellPadding: '16px 16px',
    },
  },
}
